name: weather
description: A Flutter weather app.
publish_to: 'none'
version: 0.0.1
repository: https://github.com/LingCalvin/weather_app

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  geolocator: ^9.0.2
  intl: ^0.18.0
  json_annotation: ^4.8.0
  meta: ^1.8.0
  package_info_plus: ^3.0.3
  path_provider: ^2.0.13
  provider: ^6.0.5
  hydrated_bloc: ^9.1.0
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  melos: ^2.9.0

flutter:
  uses-material-design: true
