name: nws_api
version: 0.0.1
description: A basic client for the NWS API.
repository: https://github.com/LingCalvin/weather_app
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  mockito: ^5.3.2
  test: ^1.23.1
