name: weather_repository
repository: https://github.com/LingCalvin/weather_app
publish_to: 'none'

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  nws_api:
    path: ../nws_api
  quiver: ^3.2.1

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.3
  json_serializable: ^6.6.1
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.23.1
